### ISSUE TITLE
Recursive sink missing return

### ISSUE THREAD

**Issue by andrewchambers** [polezaivsani/rscp#1]
I noticed recursive sink does not return on E message. This means directories deeper than 1 will not work when sinking to a remote.

See https://github.com/polezaivsani/rscp/blob/master/rscp.go#L133

**Comment by polezaivsani** [comment]
Fixed in f4cd2aa. Thanks, Andrew!

**Comment by andrewchambers** [comment]
Thanks, I'm doing some tests now and will let you know if i find any more stuff. :)
