### ISSUE TITLE
Full path not passed to sendDir in send

### ISSUE THREAD

**Issue by andrewchambers** [polezaivsani/rscp#2]
https://github.com/polezaivsani/rscp/blob/master/rscp.go#L409

I think 

send(path.Join(dir.Name(), child.Name())); isFatal(err)

should be 

send(path.Join(fullDirPath, child.Name())); isFatal(err)

Otherwise when recursing you lose the correct path prefix.

**Comment by polezaivsani** [comment]
I don't see how we're losing something here - dir.Name() is directory's
full path (originating from send's argument, which is an absolute
path).

Confusion may come from the fact that os.FileInfo.Name() returns a
base name, while os.File.Name() - whatever was passed to os.File.Open().

**Comment by andrewchambers** [comment]
Oh, totally my mistake :) . Its actually a bug in my code, Thanks!
